config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users, only: [] do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
  end

  root to: 'pages#home'

  resources :places, except: %i[destroy edit update] do
    resources :photos, only: %i[create]
    resources :markers, only: %i[create]
    resources :lists, only: :create
    resources :reviews, only: :create
  end

  resources :lists, only: %i[show index]
  resources :photos, only: :show do
    member do
      post :like
    end
  end


  get '/tagged', to: "places#tagged", as: :tagged
end

app/views/shared/_banner.html.erb
<div class="banner" style='background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1552334823-ca7f70376914?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070);'>
  <div class="container text-center">
    <h1 class="green">Photo Ronin</h1>
    <h3>Discover new places to take your photos</h3>
    <a class="btn btn-ghost my-5" href="/places">Explore now</a>
  </div>
</div>

app/views/shared/_button.html.erb
<%= link_to "Create", "#", class: "btn btn-ghost" %>

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" data-action="slid.bs.carousel->carousel-map#selectPin" data-bs-interval="false">
  <% if @place.photos.any? %>
    <div class="carousel-inner">
      <div class="carousel-item active" data-id="<%= @place.photos.first.id %>">
        <% first_photo = @place.photos.first %>
        <span class="helper"></span>
        <img class="d-block w-100" src="<%= cl_image_path(first_photo.photo.key) %>" />
      </div>
      <% @place.photos[1..-1].each do |photo|%>
      <div class="carousel-item" data-id="<%= photo.id %>">
        <img class="d-block w-100" src="<%= cl_image_path(photo.photo.key) %>" />
      </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  <% else %>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="<%= image_path('Ronin.jpg') %>" />
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><i class="fas fa-times light-gray"></i>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_home_card.html.erb
<% if photo.photo.attached? %>
  <div class="card-home mb-2 mx-1">

    <div class="position-absolute btn-like-place">
      <button style="background: rgba(0,0,0,0); border: none">
        <div class="flex-column icon-active">

          <%# <i class="icon-card white fas fa-heart"</i> %>
          <%#= photo.cached_votes_total %>
          <%#= raise %>
          <%# <button data-action="click->like#photoLike"class="like-button"
            <div class="flex-column icon-active" %>
          <%#= link_to like_photo_path(photo), method: :post, remote: true do %>
            <%# <i class="fas fa-heart <%= 'text-danger' if current_user&.liked?(photo) %></i>
          <%# <% end %>
          <%# </div>
          <%# </button> %>

        </div>
      </button>
    </div>

    <div class="position-relative">
      <% if photo.user.instagram_url %>
        <p class="position-absolute author-tag">by <a href="https://<%= photo.user.instagram_url %>"><%= photo.user.name %></a></p>
      <% else %>
        <p class="position-absolute author-tag"><%= photo.user.name %></p>
      <% end %>
      <img src="<%= cl_image_path(photo.photo.key) %>" class="w-100"/>
      <%= link_to '', place_path(photo.place), class: 'card-trip-link' %>
    </div>

    <div class="container mt-3 my-4">
      <% photo.place.tag_list.each do |tag| %>
        <%= link_to tag, tagged_path(tag: tag), class: 'tag-text btn btn-ghost mb-2' %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="card-home mb-2 mx-1">
    <div class="position-relative">
      <img src="<%= image_path('Ronin.jpg') %>" class="w-100"/>
      <%= link_to '', place_path(photo.place), class: 'card-trip-link' %>
    </div>
    <div class=" container mt-3 my-4">
      <% photo.place.tag_list.each do |tag| %>
        <%= link_to tag, tagged_path(tag: tag), class: 'tag-text btn btn-ghost mb-2' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_menu.html.erb
<div class="fixed-bottom bg-black pb-4" data-photo-popup-target="menu">
  <div class="d-flex justify-content-around text-center align-items-start mx-1 pt-3">
    <%= link_to root_path do %>
      <div class="icon-active">
        <i class="icon-big light-gray fas fa-home"></i>
      </div>
    <% end %>

    <%= link_to places_path do %>
      <div class="icon-active">
        <i class="icon-big light-gray fas fa-search"></i>
      </div>
    <% end %>

    <% if current_user %>
      <div class="btn-add-list" data-controller="new-list">
        <button class="btn-add" data-new-list-target="popupButton" data-action="click->new-list#showForm" style="background: rgba(0,0,0,0); border: none">
        <div class="icon-active">
          <i class="icon-plus light-gray fas fa-plus"></i>
        </div>
        </button>
        <%= render 'shared/new_place', place: @new_place %>
      </div>
    <% end %>


    <% if current_user %>
      <%= link_to user_dashboard_path(current_user) do %>
        <div class="icon-active">
          <i class="icon-big light-gray fas fa-list"></i>
        </div>
      <% end %>
    <% end %>

      <% if current_user %>
      <%= link_to lists_path do %>
        <div class="icon-active">
          <i class="icon-big light-gray fas fa-user"></i>
        </div>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <div class="icon-active">
          <i class="icon-big light-gray fas fa-user"></i>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/shared/_menu_mobile.html.erb
<% if current_user %>
  <div class="fixed-bottom menu-mobile">
    <ul>
      <div class="grid grid-icon text-center px-3 py-3">
        <li><%= link_to root_path do %>
          <div class="flex-column icon-active">
            <i class="icon-big light-gray fas fa-images mb-1"></i>
            <p class="icon-text">Featured</p>
          </div>
          <% end %>
        </li>
        <li><%= link_to places_path do %>
          <div class="flex-column icon-active">
            <i class="icon-big light-gray fas fa-search mb-1"></i>
            <p class="icon-text">Search</p>
          </div>
          <% end %>
        </li>
        <li>
          <button data-new-list-target="popupButton" data-action="click->new-list#showForm" style="background: rgba(0,0,0,0); border: none">
              <div class="flex-column icon-active">
                <i class="icon-big light-gray fas fa-plus"></i><p class="icon-text">New</p>
              </div>
          </button>
        </li>
        <li><%= link_to user_dashboard_path(current_user) do %>
          <div class="flex-column icon-active">
            <i class="icon-big light-gray fas fa-heart mb-1"></i>
            <p class="icon-text">Paths</p>
          </div>
          <% end %>
        </li>
        <li><%= link_to lists_path do %>
          <div class="flex-column icon-active">
            <i class="icon-big light-gray fas fa-list mb-1"></i>
            <p class="icon-text">Discover</p>
          </div>
          <% end %>
        </li>
      </div>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= render 'shared/search' %>
</div>

app/views/shared/_new_list.html.erb
<h2 class="mb-3">Add to a list</h2>
<%= simple_form_for [@place,@list] do |f| %>
  <%= f.input :title, label: false , input_html: { class: "input mt-3 list-input"  }, placeholder: "Name list" %>
  <%= f.submit 'Add', class: 'btn btn-ghost mt-3 position-absolute position-add', item_wrapper_class: 'd-flex'%>
<% end %>

app/views/shared/_new_marker.html.erb
<h2 class="mb-3">Select a list</h2>
<%= simple_form_for [place, marker] do |f| %>
  <%= f.association :list, collection: lists, input_html: { class: "input border-green border list-input" }, label:false, include_blank: false %>
  <%= f.submit 'Add',class: 'btn btn-ghost mt-3 position-absolute position-add-btn'%>
<% end %>

app/views/shared/_new_place.html.erb
<div class="container text-center bg-black btn-close-relative" id="form-list" data-new-list-target="formList">
  <div class="vertical-center" data-controller="form-toggle">
    <h3 class="mb-3">Add place</h3>
    <%= simple_form_for place do |f| %>
      <%= f.input :name, input_html: { class: "input input-background text-center" }, label: false, placeholder: 'Place description' %>
      <h3 class="mt-5">Select category</h3>
      <fieldset class="form-group radio_buttons required snippet_category">
        <div class="category-wrapper">
          <input type="hidden" name="place[tag_list][]" value="">
          <% ActsAsTaggableOn::Tag.all.each do |tag| %>
          <div class="category-item mt-2 text-center">
            <input class="form-check-input check_boxes required category-selector" type="checkbox" value="<%= tag.name %>" name="place[tag_list][]" id="snippet_category_id_<%= tag.id %>">
            <label class="form-check-label collection_radio_buttons" for="snippet_category_id_<%= tag.id %>"><%= tag.name %></label>
          </div>
          <% end %>
        </div>
      </fieldset>

      <%#= f.input :tag_list,
                value_method: :name,
                legend_tag: false,
                as: :check_boxes,
                collection: ActsAsTaggableOn::Tag.all,
                collection_wrapper_tag: 'div',
                collection_wrapper_class: 'category-wrapper',
                item_wrapper_class: 'category-item',
                input_html: {class: 'category-selector'} %>
      <h3 class="mt-4 mb-3">Select address</h3>
      <%# using geocoder (comment this part and change the photos_controller.rb) %>
      <%= f.input :address, label: false, input_html: { class: "input input-background text-center" } %>

      <%# Old input method %>
      <%#= f.input :address, label: false,
            wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] }, class: 'mt-3' },
            input_html: { data: { geocoder_target: 'address' }, class: 'd-none input-small mt-3' } %>
      <%= f.submit 'Add', class: 'btn btn-ghost mt-3' %>
    <% end %>
  </div class="pb-4">
  <button data-action="click->new-list#showForm" class='btn-close'><i class="fas fa-times icon-scale"></i></button>
</div>
<div style="position: relative">
  <div data-new-list-target="background"></div>
</div>

app/views/shared/_old_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%# <%= link_to "#", class: "navbar-brand" do %>
      <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <%# <% end %>
    <%= render 'shared/search' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span><i class="fas fa-user light-gray"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto d-none">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Profile", "#", class: "nav-link white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_place_card.html.erb
<div class="card-trip mb-2 mx-1 w-100">
  <img src="<%= place.photos.any? ? cl_image_path(place.photos.first.photo.key) : image_path('Ronin.jpg') %>" />
  <%= link_to '', place_path(place), class: 'card-trip-link' %>
  <div class="card-trip-infos h-100">
    <div class="position-relative p-2 mb-3">
      <div class="d-flex justify-content-between align-items-center">
        <h3 class="bold"><%= place.name %></h3>
        <% if place.average_review > 0 %>
          <h4><%= place.average_review %>  <i class="fas fa-star green bold"></i></h4>
        <% else %>
          <h4 class="bold">No Review</h4>
        <% end %>
      </div>
      <h4 class="green mb-4"><%= place.address.split(',')[0..1].join(',') %></h4>
      <div class="mt-4">
        <% place.tag_list.each do |tag| %>
          <%= link_to tag, tagged_path(tag: tag), class: 'tag-text btn btn-ghost mb-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>