config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :users, only: [] do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
  end

  root to: 'pages#home'

  resources :places, except: %i[destroy edit update] do
    resources :photos, only: %i[create]
    resources :markers, only: %i[create]
    resources :lists, only: :create
    resources :reviews, only: :create
  end

  resources :lists, only: %i[show index]
  resources :photos, only: :show do
    member do
      post :like
    end
  end


  get '/tagged', to: "places#tagged", as: :tagged
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :markers
  has_many :lists, through: :markers
  has_many :photos
  has_many :reviews
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # include PgSearch::Model
  # pg_search_scope :search_by_address_and_name,
  #                 against: %i[address name],
  #                 using: {
  #                   tsearch: { prefix: true }
  #                 }
  validates :name, presence: true
  validates :address, presence: true

  acts_as_taggable_on :tags
  # making tag_list in Place attribute usuable in the seeds

  def average_review
    # ratings = self.reviews.map { |review| review.rating}
    ratings = self.reviews.map(&:rating)

    return 0 if ratings.empty? || ratings.nil?

    ratings.sum.fdiv(self.reviews.count).round(1)
  end

  CATEGORIES = ["Urban", "Nature", "Modern", "Traditional", "Day", "Night"]
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :form_instances, only: :show

  def index
    @places = if params[:address].present?
                # policy_scope(Place.search_by_address_and_name(params[:q]))
                policy_scope(Place.near(params[:address], 2))
              else
                policy_scope(Place.all)
              end

    @places = if params[:search].nil? || params[:search][:tag_list].count <= 1
                @places
              else
                @places.tagged_with(params[:search][:tag_list][1..])
              end
    @pins = create_markers(@places)
  end

  def show
    @place = Place.find(params[:id])
    authorize @place
    @lists = current_user.lists.where.not(id: @place.lists).order(created_at: :desc) if current_user
    # @pin = create_marker(@place)
    @pin = create_photo_pins(@place)
  end

  def create
    @place = Place.new(place_params)
    authorize @place

    # using geocoder (comment this part and change the new_place.html.erb)
    @geocoder_info = Geocoder.search(params[:place][:address])[1]
    if @geocoder_info
      @place.latitude = @geocoder_info.latitude
      @place.longitude = @geocoder_info.longitude
      @place.address = @geocoder_info.address
    end
    ##

    if @place.save
      redirect_to place_path(@place), notice: "#{@place.name} has been added"
    else
      if Place.where(name: @place.name).any?
        redirect_to place_path(Place.where(name: @place.name).first), notice: "#{@place.name} already exists"
      else
        redirect_to places_path, notice: "Please enter a valid address"
      end
    end
  end

  def tagged
    if params[:tag].present?
      @places = Place.tagged_with(params[:tag])
    else
      @places = Place.all
    end
    authorize @places
    @pins = create_markers(@places)
    render 'places/index'
  end

  private

  def create_markers(places)
    places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window: render_to_string(partial: 'places/info_window', locals: { place: place }),
        custom_marker: render_to_string(partial: 'places/marker', locals: { photo: place })
      }
    end
  end

  def create_marker(place)
    {
      lat: place.latitude,
      lng: place.longitude,
      info_window: render_to_string(partial: 'places/info_window', locals: { place: place }),
      custom_marker: render_to_string(partial: 'places/marker', locals: { photo: place })
    }
  end

  def create_photo_pins(place)
    if place.photos.any?
      place.photos.map do |photo|
        {
          lat: photo.latitude,
          lng: photo.longitude,
          image_url: helpers.cl_image_path(photo.photo.key),
          info_window: render_to_string(partial: 'places/info_window_photo', locals: { photo: photo }),
          custom_marker: render_to_string(partial: 'places/marker', locals: { photo: photo })
        }
      end
    else
      [{
        lat: place.latitude,
        lng: place.longitude,
        info_window: render_to_string(partial: 'places/info_window', locals: { place: place }),
        custom_marker: render_to_string(partial: 'places/marker', locals: { photo: place })
      }]
    end
  end



  def place_params
    params.require(:place).permit(:name, :address, tag_list: [])
  end

  def form_instances
    @list = List.new
    @review = Review.new
    @marker = Marker.new
    @photo = Photo.new
  end
end

app/views/places/_info_window.html.erb
<div class="card-map">
  <%= link_to "", place_path(place), class: 'card-category-link' %>
  <img src="<%= place.photos.any? ? cl_image_path(place.photos.first.photo.key) : image_path('Ronin.jpg') %>" />

  <div class="infos-small">
    <div class="description-capacity p-3">
      <h3><%= place.name %></h2>
      <div class="d-flex justify-content-between">
        <p class="green"><i class="fas fa-map-marker"></i> <%= place.address %></p>
        <% if place.average_review > 0 %>
          <p class="bold"><%= place.average_review %>  <i class="fas fa-star green"></i></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/_info_window_photo.html.erb
<div class="card-map">
  <img src="<%= photo.photo.attached? ? cl_image_path(photo.photo.key) : image_path('Ronin.jpg') %>" />
</div>

app/views/places/_map.html.erb
<div class="map" height="100%">
  <div style="width: 100vw; height: calc(100vh - 140px - 56px); margin: 0; padding: 0"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= marker.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/places/_map_show.html.erb
<div style="width: 100%; height: 47vh; margin: 0; padding: 0"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= marker.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/places/_marker.html.erb
<% if photo %>
  <%= image_tag 'marker.png', data: {id: photo.id, carousel_map_target: 'marker'} %>
<% else %>
  <%= image_tag 'marker.png' %>
<% end %>

app/views/places/_new_photo.html.erb
<div class="container">
  <h2 class="mt-4">Share your photo of <%= place.name %></h2>
  <%= simple_form_for [@place, @photo] do |f| %>
    <div class="mt-3">
      <%= f.input :photo, as: :file, label: false, input_html: { class: "input input-photo" } %>
      <%= f.submit 'Add', class: 'btn btn-ghost'%>
  </div>
  <% end %>
</div>

app/views/places/_photo_popup.html.erb
 <div id="carouselExampleIndicators" class="carousel slide d-none popup-carousel" data-bs-ride="carousel" data-photo-popup-target="photo">
  <div class="carousel-inner">
    <% if place.photos.any? %>
        <div class="carousel-item active popup-photo" data-photo-popup-target="active">
          <img src="<%= cl_image_path(place.photos.first.photo.key) %>" alt="">
        </div>
      <% place.photos[1..-1].each_with_index do |photo, index| %>
        <div class="carousel-item popup-photo" data-photo-popup-target="nonActive">
          <img src="<%= cl_image_path(photo.photo.key) %>" alt="">
        </div>
      <% end %>
    <% end %>
  </div>
  <% if place.photos.count > 1 %>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  <% end %>
  <button data-action="click->photo-popup#show" class='btn-close'><i class="fas fa-times icon-scale"></i></button>
</div>

app/views/places/_place_horizontal_card.html.erb
<%# <img class="avatar" src=<%= list.photo.attached? ? cl_image_path(list.photo.key) : '/assets/ronin.jpg' %>>
<%# <%= link_to '', list_path(list), class: 'card-trip-link' %>
<div class="d-flex justify-content-between align-items-center background px-2">
  <div class="avatar-large">
    <img class="small-img" src=<%= place.photos.any? ? cl_image_path(place.photos.first.photo.key) : '/assets/Ronin.jpg' %> /></div>
  <div class="mt-3 me-2">
    <h3 class="bold"><%= place.name %></h3>
    <h4 class="green mb-3"> <%= place.address %> </h4>
  </div>
  <div>
    <h4 class="rating-size">5.0  <i class="fas fa-star green"></i></h4>
  </div>
</div>

app/views/places/index.html.erb
<%= render 'shared/navbar' %>
<div data-controller="map-toggle" class="toggle-button-container">
  <button data-map-toggle-target="button" class="text-center btn-center toggle-button" data-action="click->map-toggle#mapDisplay">
    See Map
  </button>
  <div class="container review-form" data-map-toggle-target="list">
    <div class="grid">
      <% if @places.any? %>
        <% @places.each do |place| %>
          <div class="card-trip d-flex align-items-stretch">
            <%= render 'shared/place_card', place: place %>
          </div>
        <% end %>
      <% else %>
        No places.
      <% end %>
    </div>
  </div>
  <div data-map-toggle-target="map">
    <%= render 'map', marker: @pins %>
  </div>
</div>

app/views/places/show.html.erb
<div class="position-relative">
  <div class="container margin-bottom" data-photo-popup-target="page">
    <div class="card-trip mt-3">
      <%# TODO Made this placeholder for "LIKE", not functional yet %>
      <% if current_user %>
        <div class="position-absolute btn-add-list me-3 mt-2" data-controller="new-list">
          <button data-new-list-target="popupButton" data-action="click->new-list#showForm" style="background: rgba(0,0,0,0); border: none">
            <div class="d-flex align-items-start icon-active white opacity">
              <i class="icon-card white fas fa-plus me-1"></i>
              <h4> Add to a list</h4>
            </div>
          </button>
          <div class="container text-center bg-black btn-close-relative" id="form-list" data-new-list-target="formList">
            <div data-new-list-target="background"></div>
            <div class="vertical-center-list" data-controller="form-toggle">
              <% if @lists.any? %>
                <div data-form-toggle-target="list" class='d-none'>
                  <%= render 'shared/new_marker', place: @place, marker: @marker, lists: @lists %>
                </div>
                <div data-form-toggle-target="new">
                  <%= render 'shared/new_list', list: @list %>
                </div>
                <button data-form-toggle-target="button" data-action="click->form-toggle#formDisplay" class='btn btn-ghost-solid mt-3 position-absolute position-existing-btn'>Existing list</button>
              <% else %>
                <%= render 'shared/new_list', list: @list %>
              <% end %>
            </div>
            <button data-action="click->new-list#showForm" class='btn-close'><i class="fas fa-times icon-scale"></i></button>
          </div>
        </div>
      <% end %>

      <div class="container">
        <div class="position-relative p-2 mb-3">
          <div class="d-flex justify-content-between align-items-end pt-2">
            <h3 class="bold mt-1 "><%= @place.name %></h3>
            <h4 class=""><%= @place.average_review %>  <i class="fas fa-star green bold"></i></h4>
          </div>
          <h4>
            <% if @place.geocode %>
              <%= link_to "https://www.google.com/maps/dir/#{@place.geocode.join(',')}", class: "green mb-2" do %>
                <i class="fas fa-map-marked-alt"></i> <%= @place.address.split(',')[0..1].join(',') %>
              <% end %>
            <% else %>
              <i class="fas fa-map-marked-alt"></i> <%= @place.address %>
            <% end %>
          </h4>
          <div class="mt-4">
            <% @place.tag_list.each do |tag| %>
              <%= link_to tag, tagged_path(tag: tag), class: 'tag-text btn btn-ghost' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div data-controller="carousel-map">
      <%= render 'shared/carousel', place: @place %>
      <%= render 'map_show', marker: @pin %>
    </div>

    <div class="mt-5 mb-5">
      <%= render 'new_photo', place: @place %>
    </div>
    <div class="container">
    <div class="d-flex justify-content-between mt-3">
      <h2>Reviews</h2>
    </div>
    <div class="position-relative review-form">
      <%= simple_form_for [@place, @review] do |f| %>
        <%= f.input :content,
                    class: "form-control-custom rounded-corner input-background",
                    rows: 5,
                    label: false,
                    id: "form-list",
                    placeholder: "Your comment",
                    input_html: { autocomplete: "Comment" } %>
        <div class="star-rating">
          <% 5.times do |i| %>
            <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
          <% end %>
        </div>
        <%= button_tag type: "submit", class: "btn btn-ghost position-absolute position-submit-review" do %>
          Post
        <% end %>
      <% end %>
    </div>
    <% @place.reviews.each do |review| %>
      <div class="light-gray pb-4">
        <div class="d-flex justify-content-between align-items-top">
          <div class="icon-name d-flex justify-content-start align-items-center">
            <div class="icon">
              <img class="avatar" src=<%= review.user.photo.attached? ? cl_image_path(review.user.photo.key) : image_path('Ronin.jpg') %> />
            </div>
            <div class="reviews-name ms-2">
              <p class="h4 white mb-0 bold align-middle"><%= review.user.name %></p>
              <p class="gray"><%= time_ago_in_words(review.created_at) %> ago</p>
            </div>
          </div>
          <div class="reviews-star">
            <% (review.rating).times do%>
              <i class="icon-star green fas fa-star"></i>
            <% end %>
          </div>
        </div>
      </div>
      <p class="white reviews-content mb-3"><%= review.content %></p>
      <hr>
      <% end %>
    </div>
  </div>
</div>